-- Add a stable, opaque public identifier for users.
-- The internal Better Auth id (UUID v7, sequential) is never exposed to the frontend.
-- public_id is a random UUID v4 generated by PostgreSQL — non-sequential, non-guessable.
-- The DEFAULT clause covers both existing rows and all future inserts without application code.

ALTER TABLE "auth"."user"
  ADD COLUMN "public_id" text NOT NULL DEFAULT gen_random_uuid();

ALTER TABLE "auth"."user"
  ADD CONSTRAINT "user_public_id_unique" UNIQUE ("public_id");
