import '@poppinss/ts-exec'
import 'reflect-metadata'
import { mkdir, readdir, writeFile } from 'node:fs/promises'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const { Ignitor } = await import('@adonisjs/core')

process.env.NODE_ENV ||= 'test'

const __dirname = dirname(fileURLToPath(import.meta.url))
const appRoot = resolve(__dirname, '..')
const appRootUrl = new URL('../', import.meta.url)
const clientOutputDir = resolve(appRoot, '.adonisjs/client/registry')
const inertiaPagesDir = resolve(appRoot, 'inertia/pages')
const serverOutputDir = resolve(appRoot, '.adonisjs/server')

function buildParams(tokens) {
  const dynamicTokens = tokens.filter(
    (token) => token.type === 1 || token.type === 2 || token.type === 3
  )
  const tuple = dynamicTokens
    .map((token) => {
      if (token.type === 2) {
        return 'ParamValue[]'
      }

      return token.type === 3 ? 'ParamValue?' : 'ParamValue'
    })
    .join(', ')
  const params = dynamicTokens
    .map((token) => {
      if (token.type === 2) {
        return "'*': ParamValue[]"
      }

      return token.type === 3 ? `${token.val}?: ParamValue` : `${token.val}: ParamValue`
    })
    .join('; ')

  return {
    paramsShape: params ? `{ ${params} }` : '{}',
    paramsTuple: `[${tuple}]`,
  }
}

function createClientDataContent() {
  return `/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type InertiaMiddleware from '#core/common/middlewares/inertia_middleware'

export namespace Data {
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
`
}

function createClientManifestContent() {
  return `/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
`
}

function createImporter() {
  return (filePath) => {
    if (filePath.startsWith('./') || filePath.startsWith('../')) {
      return import(new URL(filePath, appRootUrl).href)
    }

    return import(filePath)
  }
}

function createIndexContent(routes) {
  const entries = routes
    .map(
      (route) => `  ${JSON.stringify(route.name)}: {
    methods: ${JSON.stringify(route.methods)},
    pattern: ${JSON.stringify(route.pattern)},
    tokens: ${JSON.stringify(route.tokens)},
    types: placeholder as Registry[${JSON.stringify(route.name)}]['types'],
  }`
    )
    .join(',\n')

  return `/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
${entries},
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
`
}

function createPagesContent(pages) {
  const entries = pages
    .map(
      (page) =>
        `    ${JSON.stringify(page.name)}: ExtractProps<(typeof import(${JSON.stringify(page.importPath)}))['default']>`
    )
    .join('\n')

  return `import '@adonisjs/inertia/types'

import type React from 'react'
import type { Prettify } from '@adonisjs/core/types/common'

type ExtractProps<T> =
  T extends React.FC<infer Props>
    ? Prettify<Omit<Props, 'children'>>
    : T extends React.Component<infer Props>
      ? Prettify<Omit<Props, 'children'>>
      : never

declare module '@adonisjs/inertia/types' {
  export interface InertiaPages {
${entries}
  }
}
`
}

function createSchemaContent(routes) {
  const entries = routes
    .map((route) => {
      const { paramsShape, paramsTuple } = buildParams(route.tokens)

      return `  ${JSON.stringify(route.name)}: {
    methods: ${JSON.stringify(route.methods)}
    pattern: ${JSON.stringify(route.pattern)}
    types: {
      body: any
      paramsTuple: ${paramsTuple}
      params: ${paramsShape}
      query: any
      response: any
      errorResponse: any
    }
  }`
    })
    .join('\n')

  return `/* eslint-disable prettier/prettier */
export type ParamValue = string | number | bigint | boolean

export interface Registry {
${entries}
}
`
}

function createServerRoutesContent(routes, imports, types) {
  return [
    `import '@adonisjs/core/types/http'`,
    ...imports,
    '',
    ...types,
    '',
    'export type ScannedRoutes = {',
    routes,
    '}',
    `declare module '@adonisjs/core/types/http' {`,
    '  export interface RoutesList extends ScannedRoutes {}',
    '}',
  ].join('\n')
}

function createTreeContent() {
  return `/* eslint-disable prettier/prettier */
export type ApiDefinition = Record<string, any>
`
}

function flattenRoutes(routesByDomain) {
  const groupedRoutes = new Map()

  for (const routes of Object.values(routesByDomain)) {
    for (const route of routes) {
      const name = route.name || route.pattern
      const existing = groupedRoutes.get(name)

      if (existing) {
        if (existing.pattern !== route.pattern) {
          throw new Error(
            `Route "${name}" has multiple patterns: "${existing.pattern}" and "${route.pattern}"`
          )
        }

        for (const method of route.methods) {
          if (!existing.methods.includes(method)) {
            existing.methods.push(method)
          }
        }

        continue
      }

      groupedRoutes.set(name, {
        methods: [...route.methods],
        name,
        pattern: route.pattern,
        tokens: sanitizeTokens(route.tokens),
      })
    }
  }

  return [...groupedRoutes.values()]
}

async function loadInertiaPages(directoryPath) {
  const directoryEntries = await readdir(directoryPath, { withFileTypes: true })
  const pages = []

  for (const entry of directoryEntries) {
    const absolutePath = resolve(directoryPath, entry.name)

    if (entry.isDirectory()) {
      pages.push(...(await loadInertiaPages(absolutePath)))
      continue
    }

    if (!entry.isFile() || !entry.name.endsWith('.tsx')) {
      continue
    }

    const pageRelativePath = relative(inertiaPagesDir, absolutePath).replaceAll('\\', '/')
    const pageName = pageRelativePath.replace(/\.tsx$/, '')
    const importPath = `../../inertia/pages/${pageName}.tsx`

    pages.push({
      importPath,
      name: pageName,
    })
  }

  return pages.sort((left, right) => left.name.localeCompare(right.name))
}

async function loadRouteArtifacts() {
  const app = new Ignitor(appRootUrl, { importer: createImporter() })
    .tap((application) => {
      application.booting(async () => {
        await import('#start/env')
      })
    })
    .createApp('web')

  try {
    await app.init()
    await app.boot()

    for (const preload of app.rcFile.preloads) {
      if (preload.environment.includes('web')) {
        await preload.file()
      }
    }

    const router = await app.container.make('router')
    if (!router.commited) {
      router.commit()
    }

    const serverRoutes = router.toJSON()
    const { imports, routes, types } = router.generateTypes(2)

    return {
      clientRoutes: flattenRoutes(serverRoutes),
      serverRoutes,
      serverTypes: createServerRoutesContent(routes, imports, types),
    }
  } finally {
    await app.terminate()
  }
}

function sanitizeTokens(tokens) {
  return tokens.map((token) => ({
    end: token.end,
    old: token.old,
    type: token.type,
    val: token.val,
  }))
}

const artifacts = await loadRouteArtifacts()
const pages = await loadInertiaPages(inertiaPagesDir)

await mkdir(serverOutputDir, { recursive: true })
await mkdir(clientOutputDir, { recursive: true })
await Promise.all([
  writeFile(resolve(appRoot, '.adonisjs/client/data.d.ts'), createClientDataContent()),
  writeFile(resolve(appRoot, '.adonisjs/client/manifest.d.ts'), createClientManifestContent()),
  writeFile(resolve(serverOutputDir, 'pages.d.ts'), createPagesContent(pages)),
  writeFile(resolve(serverOutputDir, 'routes.d.ts'), artifacts.serverTypes),
  writeFile(resolve(serverOutputDir, 'routes.json'), JSON.stringify(artifacts.serverRoutes)),
  writeFile(resolve(clientOutputDir, 'index.ts'), createIndexContent(artifacts.clientRoutes)),
  writeFile(resolve(clientOutputDir, 'schema.d.ts'), createSchemaContent(artifacts.clientRoutes)),
  writeFile(resolve(clientOutputDir, 'tree.d.ts'), createTreeContent()),
])

console.log(
  `Generated route artifacts for ${artifacts.clientRoutes.length} route(s) and ${pages.length} Inertia page type(s)`
)
